version: '3.9'
services:
  api:
    container_name: safety-beacon-api
    ports:
      - '8080:8080' # map: local:container
    # restart: always # Restarts the service whenever any defined configuration changes
    env_file:
      - .env
    # environment:
    #   - SUPER_SECRET_KEY=${SUPER_SECRET_KEY}
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: dev
    volumes:
      - .:/app
    # depends_on:
    #   - db
